### PR TITLE
Remove BAZEL build in ray-operator project

### PR DESCRIPTION
**Pull request by chenk008**
Remove bazel build. Go module is the official dependency manage tool. Go build is the official build kit. 

#close https://github.com/ray-project/ray-contrib/issues/26

### CODE REVIEW

**Comment by Jeffwan** [comment]
This PR will be unblocked until https://github.com/ray-project/ray-contrib/pull/31 is merged.

**Comment by Jeffwan** [comment]
Looks good to me.

**Review by Jeffwan — APPROVED** [review]

**Comment by Jeffwan** [comment]
#31 is merged and CI issue is fixed. @chenk008 Can you rebase master changes?

**Comment by chenk008** [comment]
@Jeffwan I have rebased master.

**Review by akanso — APPROVED** [review]

**Review by Jeffwan — APPROVED** [review]

**Pull request merged**
