### PR TITLE
Ray Autoscaler integrate with Ray K8s Operator

### PR DESCRIPTION
**Pull request by Qstar**
## Why are these changes needed?

1.fix the problem falling behind in terms of scaling features; autoscaling not up to par with other Clouds

Main modifications:
* Add Operator node provider.
* Update logic of Ray Operator.

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by zhe-thoughts** [comment]
Thanks for the contribution @Qstar. Is this on top of #1 ? cc @raulchen @caitengwei

**Comment by akanso** [comment]
> Thanks for the contribution @Qstar. Is this on top of #1 ? cc @raulchen @caitengwei

@zhe-thoughts we based #1 (shown here: https://github.com/akanso/ray-contrib/tree/design-1b/msft-operator/ray-operator) on top of the schema in #2 , and then we modified it to use `pod template` instead of [extensions](https://github.com/alipay/ray-contrib/blob/autoscaler_operator/antgroup/deploy/ray-operator/api/v1alpha1/raycluster_types.go#L78)  as per the discussions in [this google doc](https://docs.google.com/document/d/1DPS-e34DkqQ4AeJpoBnSrUM8SnHnQVkiLlcmI4zWEWg/edit?ts=5f906e13#heading=h.825wx4vpnxmb)

**Comment by Qstar** [comment]
> Thanks for the contribution @Qstar. Is this on top of #1 ? cc @raulchen @caitengwei

This PR(https://github.com/ray-project/ray-contrib/pull/2) is for integrating Autoscaler with Operator( already in the existing repo), and the PR(https://github.com/ray-project/ray-contrib/pull/1) makes modifications based on PR(https://github.com/ray-project/ray-contrib/pull/2) (Please correct me if I'm wrong  @akanso ).

**Comment by caitengwei** [comment]
@zhe-thoughts we plan to merge #2 first, because we're using the autoscaler & operator integration in our internal scenario. And we'll collaborate with @akanso based on #1 to migrate our implementation and autoscaler integration. Is that ok to you?

**Comment by zhe-thoughts** [comment]
Thanks for explaining this @caitengwei @Qstar @akanso. The plan sounds good to me. @ericl @edoakes thoughts?

**Pull request merged**
